/// <reference types="node" />
/**
 * `_regenerate.test.ts` — a one-shot generator gated behind
 * `REGENERATE_FIXTURES=1`. It exists in the test tree only so vitest's
 * TypeScript resolution + module aliases "just work"; it does NOT run
 * in the default `npm test` invocation.
 *
 * Usage:
 *
 *   REGENERATE_FIXTURES=1 npx vitest run \
 *     src/domain/layout/__fixtures__/_regenerate.test.ts
 *
 * IMPORTANT: human review is REQUIRED before committing regenerated
 * fixtures. Diff each JSON, sanity-check the numbers, and confirm the
 * change was INTENDED. A fixture drift is otherwise a regression.
 *
 * NOTE: the `/// <reference types="node" />` directive above is a
 * FILE-LOCAL scope for node types — we deliberately do NOT add `"node"`
 * to `tsconfig.app.json`'s `types` array because the domain layer
 * MUST NOT depend on Node built-ins (see ESLint boundary rules).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { describe, it } from 'vitest';

import { computeLayout } from '../layout-engine';

import { FIXTURE_DESIGNS } from './fixtures-data';

const HERE = dirname(fileURLToPath(import.meta.url));

const REGENERATE = process.env['REGENERATE_FIXTURES'] === '1';

describe.runIf(REGENERATE)('regenerate layout fixtures (gated by REGENERATE_FIXTURES=1)', () => {
  it('writes JSON goldens for every FIXTURE_DESIGNS entry', () => {
    for (const { name, design } of FIXTURE_DESIGNS) {
      const expected = computeLayout(design, { now: () => design.createdAt });
      const fixture = {
        name,
        description:
          'Auto-generated by _regenerate.test.ts — do NOT hand-edit. See __fixtures__/README.md.',
        design,
        expected,
      };
      const path = resolve(HERE, `${name}.json`);
      writeFileSync(path, JSON.stringify(fixture, null, 2) + '\n');
       
      console.log(`wrote ${path}`);
    }
  });
});
